### PR TITLE
Added toast notifications when copy button is clicked using toastify js library.

### PR DESCRIPTION
**Pull request by Haseeeb1**
Screenshot (1249)

### CODE REVIEW

**Comment by Petsamuel** [comment]
@Haseeeb1 resolves #5

**Comment by newtoallofthis123** [comment]
is there anyway you can do it like a toast from the top left, instead of it extending the nav

**Comment by Haseeeb1** [comment]
yeah man I'll update it.

**Comment by Haseeeb1** [comment]
Done!
Screenshot (1251)

**Comment by newtoallofthis123** [comment]
Done

**Pull request merged**
